src/Entity/Order.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrderRepository")
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $created_date;

    /**
     * @var OrderItem[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="OrderItem", mappedBy="order")
     */
    private $order_items;

    /**
     * Order constructor.
     */
    public function __construct()
    {
        $this->order_items = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return int
     */
    public function getNumber(): ?int
    {
        return $this->number;
    }

    /**
     * @param int $number
     * @return $this
     */
    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * @return DateTime
     */
    public function getCreatedDate(): ?string
    {
        return $this->created_date->format('Y-m-d H:i:s');
    }

    /**
     * @param DateTime $created_date
     * @return $this
     */
    public function setCreatedDate(DateTime $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    /**
     * @return OrderItem[]|ArrayCollection
     */
    public function getOrderItems()
    {
        return $this->order_items;
    }

    /**
     * @param OrderItem $order_item
     * @return self
     */
    public function addOrderItem(OrderItem $order_item) : self
    {
        if (!$this->order_items->contains($order_item)) {
            $this->order_items[] = $order_item;
            $order_item->setOrder($this);
        }

        return $this;
    }

//    public function setOrderItem(OrderItem $order_item = null)
//    {
//        $this->order_items = $order_item;
//
//        return $this;
//    }

    /**
     * @param OrderItem $order_item
     * @return self
     */
    public function removeOrderItem(OrderItem $order_item) : self
    {
        $this->order_items->removeElement($order_item);

        return $this;
    }

    public function sumItems()
    {
        $sum_price = 0;
        foreach ($this->getOrderItems() as $order_item){
            $sum_price += $order_item->getProductPrice();
        }
        return $sum_price;
    }

//    /**
//     * @ORM\PrePersist()
//     */
//    public function prePersist()
//    {
//        $this->created_date = new \DateTime();
//    }
}

src/Entity/OrderItem.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrderItemRepository")
 */
class OrderItem
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Order
     *
     * @ORM\ManyToOne(targetEntity="Order", inversedBy="order_items", cascade={"persist"})
     * @ORM\JoinColumn(name="order_id", referencedColumnName="id", nullable=false)
     */
    private $order;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $product_name;

    /**
     * @ORM\Column(type="decimal")
     */
    private $product_price;

    /**
     * @ORM\Column(type="integer")
     */
    private $amount;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getProductName(): ?string
    {
        return $this->product_name;
    }

    /**
     * @param string $product_name
     * @return $this
     */
    public function setProductName(string $product_name): self
    {
        $this->product_name = $product_name;

        return $this;
    }

    /**
     * @return float
     */
    public function getProductPrice(): float
    {
        return $this->product_price;
    }

    /**
     * @param float $product_price
     * @return $this
     */
    public function setProductPrice(float $product_price): self
    {
        $this->product_price = $product_price;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getAmount(): ?int
    {
        return $this->amount;
    }

    /**
     * @param int $amount
     * @return $this
     */
    public function setAmount(int $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * @return Order|null
     */
    public function getOrder(): ?Order
    {
        return $this->order;
    }

    /**
     * @param Order $order
     * @return $this
     */
    public function setOrder(?Order $order): self
    {
        $this->order = $order;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('from', \DateTime::class)
            ->add('to', \DateTime::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OrderController extends AbstractController
{
    /**
     * @Route("/order", name="order")
     */
    public function index(): Response
    {
        $orders = $this
            ->getDoctrine()
            ->getRepository(Order::class)
            ->findAll();

        return $this->render('order/index.html.twig', [
            'orders' => $orders,
        ]);
    }

    /**
     * @return Response
     */
    public function filterByDate(): Response
    {
        $form = $this
            ->createFormBuilder(null)
            ->setAction($this->generateUrl('handleFilter'))
            ->add('from', DateTimeType::class, [
                'widget' => 'single_text',
            ])
            ->add('to', DateTimeType::class, [
                'widget' => 'single_text',
            ])
            ->add('search', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary'
                ]
            ])
            ->getForm();

        return $this->render('order/searchBar.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @route("/handleFilter", name="handleFilter")
     * @param Request $request
     * @return Response
     * @throws \Exception
     */
    public function handleForm(Request $request): Response
    {
        $form = $request->request->get('form');

        $orders = $this
            ->getDoctrine()
            ->getRepository(Order::class)
            ->findByDateTimeInterval(new \DateTime($form['from']), new \DateTime($form['to']));

        return $this->render('order/index.html.twig', [
            'orders' => $orders,
        ]);
    }
}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello OrderController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }

        tr {
            vertical-align: top;
        }

        td {
            text-align: center;
        }

        .custom-td {
            position: relative;
            top: -4px;
        }
    </style>

    {{ render(controller(
        'App\\Controller\\OrderController::filterByDate'
    )) }}

    <br>
    <table class="table text-center" border="1px">
        <tr>
            <th class="active text-center">Date</th>
            <th class="active text-center">Id</th>
            <th class="active text-center">Sum</th>
            <th class="text-center">Product</th>
        </tr>
        {% for order in orders %}
            <tr>
                <td>{{ order.createdDate }}</td>
                <td>{{ order.id }}</td>
                <td>{{ order.sumItems }}</td>
                <td class="custom-td">
                    <table border="1px">
                        <tr>
                            <th style="font-weight: normal;">Name</th>
                            <th style="font-weight: normal;">Amount</th>
                        </tr>
                        {% for orderItem in order.orderItems %}
                            <tr>
                                <td>{{ orderItem.productName }}</td>
                                <td>{{ orderItem.amount }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/order/searchBar.html.twig
{{ form(form) }}